### ISSUE TITLE
Not working in some ssh clients

### ISSUE THREAD

**Issue by mistguy** [Robpol86/colorclass#13]
It seems some ssh clients under windows don't respect the color settings.

I am not familiar about how to show color in terminal. Can you give me a hint?

**Comment by Robpol86** [comment]
Presumably you're sshing into linux servers from a Windows client. If that's the case then the problem is probably in the windows SSH client (though PuTTY should definitely show colors). colorclass just uses regular ansi codes for linux (http://misc.flogisoft.com/bash/tip_colors_and_formatting).

**Comment by mistguy** [comment]
Thanks for your reply, but I have tested more since the original post. In the windows ssh client, `echo -e '\e[31mNOTICE\e[0m‘` will show red color, but colorclass do not. Is there something special about colorclass?
BTW, I have to develop a program for this ssh client because most of the users are using it.

**Comment by Robpol86** [comment]
On Linux, OSX, and Cygwin colorclass does exactly that. However on Windows (running Python on windows), it doesn't. It accesses Windows APIs to change the console window's color for the next character.

You say you're developing a program for the ssh client, so that means you're running colorclass on Windows locally, not through SSH. In that case did you run colorclass.Windows.enable() as per the readme? Can you post a screenshot of colorclass not working through the interactive console?

**Comment by mistguy** [comment]
No, I put my python script in a linux host and all users are sshing into it. Below is a screenshot:
![capture](https://cloud.githubusercontent.com/assets/8522036/9805959/c12e6ba8-5871-11e5-8ce4-e120e6dc1e8f.PNG)
Notice that `'\x1b[31mTest\x1b[39m'` is generated by `{red}Test{/red}` and `'\x1b[91mTest\x1b[39m'` is generated by `{autored}{/red}`.

It seems to be an encoding problem.

**Comment by Robpol86** [comment]
That's odd. Try running `python -c "from colorclass import Color; print Color('{red}Test{/red}')"`.

![screenshot 2015-09-10 19 57 45](https://cloud.githubusercontent.com/assets/3413339/9806180/62f7e9f4-57f6-11e5-91ea-07f138ac878b.png)

**Comment by mistguy** [comment]
![capture](https://cloud.githubusercontent.com/assets/8522036/9806623/64865d36-5879-11e5-88b1-b131711b35db.PNG)

**Comment by mistguy** [comment]
http://dc3.pc6.com/qd2/pc6-SSHSecureShellClient.zip
The ssh client if you want.

**Comment by Robpol86** [comment]
39 resets the foreground color without changing the background color. I'm not sure what's going on with your system or your application using colorclass. For one thing, 39 didn't work. Is this like a super old version of Linux/SunOS/Bash/sh? Also it appears that colorclass did indeed work fine; it changed your color. It might be a bug in your Python code.

**Comment by mistguy** [comment]
I use `autored` in my python code which doesn't work in the ssh client, so it's not a bug. Maybe I should manually edit the color for the client.
