### ISSUE TITLE
.format() color injection

### ISSUE THREAD

**Issue by ThiefMaster** [Robpol86/colorclass#16]
```
>>> print(colorclass.Color('{red}XXX: {/red}{}').format('{green}moo{/green}'))
XXX: moo
```

Expected: `XXX: {green}moo{/green}` (with `XXX:` in red)
Actual: `XXX: moo` (with `XXX:` in red and `moo` in green)

This is especially annoying since it means one cannot use the `Color` class without the tag parsing.

**Comment by Robpol86** [comment]
Color.format() will return a Color instance which parses {green}, just as str.format() returns a str instance. If you don't want {green} to be parsed you'll need to feed it into str.format(). Something like `print(str(colorclass.Color('{red}XXX: {/red}{}')).format('{green}moo{/green}'))`

**Comment by ThiefMaster** [comment]
But as soon as I convert it back to a `Color` class it'll be parsed. (I'm just using the Color class to get the proper length calculation)

**Comment by Robpol86** [comment]
Hmm, true. I should fix colorclass so you can do something like `.format('{{green}}moo{{/green}}')`, which is what str.format() does.

**Comment by ThiefMaster** [comment]
a way that lets you create a Color instance without invoking the parsing logic at all would be nice, too

**Comment by Robpol86** [comment]
I'm not sure about that. My goal with colorclass was to mimic str. str.format() doesn't have such functionality. Hence why it supports escaping curly brackets with {{ and }}.

**Comment by ThiefMaster** [comment]
that last one wasn't `format`-specific, more a general suggestion to make `Color()` more flexible
