### ISSUE TITLE
Windows.enable() breaks colors

### ISSUE THREAD

**Issue by Gliptal** [Robpol86/colorclass#17]
I'm on Windows 10 (64bit), Python 3.5.1.

Calling `Windows.enable()` as per documentation actually doesn't show the colors (although it does parse the string correctly). Commenting it out yields the correct behaviour.

**Comment by Robpol86** [comment]
Can I have a screenshot of your cmd.exe window please?

**Comment by Gliptal** [comment]
![notworking](https://cloud.githubusercontent.com/assets/3907646/12822460/79a9eff4-cb68-11e5-84a5-520773940e8e.jpg)
![working](https://cloud.githubusercontent.com/assets/3907646/12822461/79b684c6-cb68-11e5-8cd0-1df63b92f9f2.jpg)

**Comment by Robpol86** [comment]
Hmm, weird. I'll have to investigate this weekend. Would be cool if cmd.exe finally supported ANSI colors natively.

**Comment by Robpol86** [comment]
Opened https://github.com/Robpol86/colorclass/issues/18 since it does indeed look like latest Windows 10 supports ANSI colors natively.
