### ISSUE TITLE
It is available bold, underline...?

### ISSUE THREAD

**Issue by Nekmo** [Robpol86/colorclass#19]
First, congratulate your work!

I wonder if there is any way to put the text bold or underlined.

Thanks!

**Comment by Robpol86** [comment]
Yep

```
In [3]: colorclass.list_tags()
Out[3]: 
[(None, '/all', None, 0),
...
 ('b', '/b', 1, 22),
...
 ('u', '/u', 4, 24),
...
 ('hibgwhite', '/hibgwhite', 107, 49)]
```

Thought underline isn't supported in many terminals so it might not work.

**Comment by Nekmo** [comment]
Thank you :)
