### ISSUE TITLE
`disable_all_colors()` not working?

### ISSUE THREAD

**Issue by liiight** [Robpol86/colorclass#21]
It's probably me being silly and it using it correctly, but from what i could gather from the docs, calling it anywhere should just disable all colors;
```
>>> from colorclass import disable_all_colors
>>> print string
←[31mbla←[39m
>>> disable_all_colors()
>>> print string
←[31mbla←[39m
>>>
```
What am I doing wrong? tried it both on Windows 7, 10 and Ubuntu...

**Comment by Robpol86** [comment]
It only disables colors used by ColorClass instances, not system wide (except on Windows where it does disable colors until you close the cmd.exe window).

**Comment by liiight** [comment]
Well I only tried to use it with ColorClass obviously, but did not see that it worked,  not on windows and not on Linux, like I said.

**Comment by Robpol86** [comment]
Ah, didn't see how you created that variable. The function disables colors for any new Color instance created afterwards, not current ones.

```
>>> string = Color.red('test')
>>> str(string)
'\x1b[31mtest\x1b[39m'
>>> disable_all_colors()
>>> string = Color.red('test')
>>> str(string)
'test'
>>> 
```

**Comment by liiight** [comment]
Ah, I see. I figured I was misusing it. It would be nice if it was documented though. I'll give this a try and report if I still have issues. Thanks!
